### ISSUE TITLE
Not support MP3 in iOS ?

### ISSUE THREAD

**Issue by HiJimChen** [Sub6Resources/chewie_audio#3]
When I play a MP3 file in iOS, the log show the bug "The getter '_duration' was called on null". It seem that the plugin use something only support video in iOS. By the way, android is worked well.

**Comment by MWanKi** [comment]
I have same error

**Comment by INDAPP** [comment]
Same error

**Comment by rashid-abdulla** [comment]
The same error persists in ios. Works smoothly on android. Any workarounds?

**Comment by DebugTheCode** [comment]
Same error here.

**Comment by FabianGroeger96** [comment]
same error does this issue have any workarounds?

**Comment by DebugTheCode** [comment]
@FabianGroeger96 I used an other plugin: `audioplayer: ^0.8.1`. I think it's more customizable and therefore more useful.

**Comment by DangKhoi1997** [comment]
Yo, the issue still there, any workaround guys ?? . I cant change other plugin like @DebugTheCode De suggested cuz i use library flutter html and it depend on chewie_audio .

**Comment by mahtab-ali** [comment]
same issue on ios even with other audio formats like wav ...

**Comment by dcarriola** [comment]
Same here, still happening 👎

**Comment by armanhadifatah** [comment]
Same here

**Comment by tneotia** [comment]
@ryan-berger and all others, I've been trying to work on this for the past couple of hours and here are my findings:
1. This seems to be an issue from the `video_player` plugin side.
2. In the `video_player` plugin file, at line 296, you can see where the duration value is supposed to get passed to the `VideoPlayerValue` object, that holds this duration value and is used in the play/pause/scrub functions. 
3. For some reason, the `case VideoEventType.initialized` never fires when loading an mp3 on iOS, which means that the duration of the file never gets passed to `VideoPlayerValue`. Some other `case`s do fire though, like `case VideoEventType.bufferingUpdate`.
4. However, if you load an mp4, the `case VideoEventType.initialized` does fire and pass a duration.
5. It seems like the platform-specific code in `video_player` is having issues with audio-only files. Without the `case VideoEventType.initialized` firing I don't know if this issue can be fixed.
6. For the sake of it, in `case VideoEventType.bufferingUpdate`, I passed the duration of a random mp3 I found online, and lo and behold, gone is the 
```
The getter '_duration' was called on null
```
error, the audio player UI displays correctly, and the audio itself plays just fine.
7. I also used the `flutter_ffmpeg` to try and get the duration of the mp3, and it works great! This can't be used in a fix AFAIK because the duration needs to be passed in the `video_player` package, but shows that it is possible to get the duration on iOS.

A lot of the method channel and platform channel code stuffs go over my head, and I think the root of the issue is buried in there somewhere. If you go to `video_player_platform_interface/method_channel_video_player.dart` in Dart packages, at line 100 ish you can see where the Flutter platform_channel code is being called. The `map` that is returned never contains a `duration` key.

**Comment by ryan-berger** [comment]
@tneotia Thank you for you analysis.

Do you think you could open up an issue for the `video_player` plugin so they can get this fixed? I'm not super well versed in how Flutter deals with platform channel code, but I'm comfortable using C++, ObjC, or Java if needs be, but it sounds like this isn't our issue and once it is fixed we can bump the version.

Am I correct in my analysis?

**Comment by tneotia** [comment]
I think you're correct, although I'm hesitant to open an issue since `video_player` is just meant to play video files, right? I don't know if they would work on a fix since technically the issue is with audio files which aren't a feature of the package. I could be wrong though, and I can open one if you think it's beneficial.
